export const PRODUCTLISTREQUEST = 'PRODUCTLISTREQUEST'
export const PRODUCTLISTSUCCESS = 'PRODUCTLISTSUCCESS'
export const PRODUCTLISTFAIL = 'PRODUCTLISTFAIL'

export const PRODUCTDETAILSTREQUEST = 'PRODUCTDETAILSTREQUEST'
export const PRODUCTDETAILSTSUCCESS = 'PRODUCTDETAILSTSUCCESS'
export const PRODUCTDETAILSTFAIL = 'PRODUCTDETAILSTFAIL'
