export const PRODUCTLISTREQUEST = 'PRODUCTLISTREQUEST'
export const PRODUCTLISTSUCCESS = 'PRODUCTLISTSUCCESS'
export const PRODUCTLISTFAIL = 'PRODUCTLISTFAIL'

export const PRODUCTDETAILSTREQUEST = 'PRODUCTDETAILSTREQUEST'
export const PRODUCTDETAILSTSUCCESS = 'PRODUCTDETAILSTSUCCESS'
export const PRODUCTDETAILSTFAIL = 'PRODUCTDETAILSTFAIL'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CHANGEVALUES_ITEM = 'CART_CHANGEVALUES_ITEM'
